<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>kubis1982.FluentResult</AssemblyName>
		<PackageId>kubis1982.FluentResult</PackageId>
		<Version>1.0.0</Version>		
		<Description>A lightweight and fluent implementation of the Result pattern for .NET, providing type-safe error handling without exceptions.</Description>
		<PackageTags>result;pattern;error-handling;fluent;functional;railway</PackageTags>
		<IsPackable>true</IsPackable>		
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENCE" Link="LICENCE" Pack="true" PackagePath=""/>
		<None Include="..\..\README.md" Pack="true" PackagePath="" />
		<None Include="..\..\docs\icon.jpg" Pack="true" PackagePath=""/>
	</ItemGroup>

</Project>
