<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>kubis1982.FluentResult.Extensions.Wolverine</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="WolverineFx" Version="5.16.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FluentResult\FluentResult.csproj" />
	</ItemGroup>

</Project>
