<Project>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Kubis1982.Result</RootNamespace>		
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

</Project>
