<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Authors>Mariusz Świątnicki</Authors>
		<PackageProjectUrl>https://github.com/kubis1982/Result</PackageProjectUrl>
		<RepositoryUrl>https://github.com/kubis1982/Result</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Version>1.1.0</Version>
		<Description>WolverineFx extensions for Result, providing message-handling and middleware integrations for WolverineFx.</Description>
		<PackageTags>result;wolverinefx;wolverine;messaging;extensions</PackageTags>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENCE" Link="LICENCE" Pack="true" PackagePath="" />
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="..\..\docs\icon.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="WolverineFx" Version="5.16.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Result\Kubis1982.Result.csproj" />
	</ItemGroup>

</Project>
