<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>kubis1982.Result.WolverineFx</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENCE" Link="LICENCE" Pack="true" PackagePath="" />
		<None Include="..\..\README.md" Pack="true" PackagePath="" />
		<None Include="..\..\docs\icon.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="WolverineFx" Version="5.16.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Result\Result.csproj" />
	</ItemGroup>

</Project>
